### ISSUE TITLE
Bug Report: Set up doesn't work for organizations with IP allowlist

### ISSUE THREAD

**Issue by maxwolffe** [atlassian/github-for-jira#411]
Hi friends,

I'm opening up this issue on the public repository so folks have the ability to upvote this issue or discover it before investing in the integration.

**Problem:** This integration does not work for organizations which have IP allowlists enabled on the GitHub side. 

**Steps to Reproduce:**
- I'm an admin/owner on both my JIRA Cloud organization and my GitHub.com organization. 
- I have enforced IP allowlist for me GitHub.com organization (my understanding is that this is a pretty common situation).
- I followed readme instructions (install app on JIRA, install on GitHub).
- When I attempt to set up the application from the JIRA side (Getting Started -> Add an organization -> jira.github.com page) I see a greyed out bar with the following text: "Unable to connect this installation. Admin access is required."

I've opened a support ticket and got the response that this is a known issue for GitHub.com organizations with IP allowlists. 

**Asks:**
- Fixing this would be amazing - if there's a work around, I'd love to understand that as well.
- While we wait for the above, would it be possible for us to update the FAQ / Pre-reqs to make this limitation more clear? I'd be happy to open a PR to do this if folks don't have cycles.

Thanks!

**Comment by jbonilla-li** [comment]
Really miss this functionality 😿

**Comment by rachellerathbone** [comment]
Hi @maxwolffe. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

I've flagged this with the 'to-triage' label so my team can discuss. We'll keep you posted on the status of this.

**Comment by maxwolffe** [comment]
@rachellerathbone - Great! Thank you!

**Comment by KatjaWass** [comment]
@rachellerathbone 
Any progress here / eta for when expected ownership has been transferred?
I have a bunch of developer who is terrible frustrated about the missing functionality. 

I've found this in Atlassian long term backlog and low priority and long term doesn't sound promising. 
https://github.com/integrations/jira/issues/411

**Comment by davidshopback** [comment]
We tried adding every atlassian IP listed [here](https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/) into the allow list, it did not help. Just in case someone wanted to try it.

**Comment by mboudreau** [comment]
Hi everyone, 

The team at Atlassian is working on this as we transition the integration from being Github owned to Atlassian owned.  At the current moment, the integration domain does currently hold a static IP address and can change at any time.  We are currently working on a solution for this and will update the information in the Github app's IP allow list when we have it available, which should update your configuration automatically. 

We're very sorry for the inconvenience, but a fix is in the works.  Please be patient :)

**Comment by KatjaWass** [comment]
@mboudreau 

This is really good news. Looking forward to hear more and if possible an approx timeline for releasing the fix would be highly appreciated. 

Have a good weekend.

**Comment by bc-shopback** [comment]
@mboudreau 

any good news on this?

**Comment by mboudreau** [comment]
@bc-shopback 
Somewhat. From a technical standpoint, we have it ready, but we haven't transitioned the infrastructure from GitHub to Atlassian just yet. We're trying to get this done ASAP and are aiming for the next 2 weeks, but we're trying to make sure that the transition will be as seamless as possible with the shortest maintenance window.

Once that's done, it should be a fairly simple change to turn it on. We're so sorry about the length of time this is taking as there are many moving parts, including legalities, security concerns and technical difficulties on both sides. We've actually hit a big milestone this week as you'll notice that this repo is now owned by Atlassian in preparation for the migration. 

We're so close and we will let you know when this is done with much fanfare on our end. Cheers!

**Comment by ui-jeremy-wu** [comment]
@mboudreau Any good news on the transition?

**Comment by mboudreau** [comment]
We've done several dry runs to make sure we don't have any issues and try to keep the downtime to a minimum.  There's still a couple of kinks to work out.  We're also trying to do the migration during the time of least activity, which is in the wee hours on sunday and monday morning.  We aren't able to do it this weekend, but I think we're on track to try to achieve it the next unless something unexpected happens.

Thanks for being patient, we're trying our best and want to make sure the migration is as smooth as possible for everyone.

**Comment by KatjaWass** [comment]
What worries me is, when I check this ticket JSWCLOUD-20626 it doesn't look like it is on the radar of Atlassian.

https://jira.atlassian.com/browse/JSWCLOUD-20626?error=login_required&error_description=Login+required&state=2af84e3f-c511-4632-9357-423314e4c169&state=cce86bec-871c-4b27-bbed-a4f57243b94f&state=33790cd4-95b3-45a1-8637-df398241fab7&state=08f00cae-398d-438c-9ae4-15692bf08325&state=61eec28c-9213-4d52-9f91-4dde44db9d6a

**Comment by thombergs** [comment]
I assure you, it is on our radar. It's actually already fixed in the new version of the app, we "just" need to migrate the app from GitHub's current version to Atlassian's new version, which we're testing right now. Should be a matter of a couple weeks now. I'll see to it that the status of the issue you linked is updated on Monday. Thanks for bringing that to our attention!

**Comment by bhakimi** [comment]
any updates on this?

**Comment by thombergs** [comment]
@bhakimi we're targeting August 22nd as the migration date. If all goes well, IP allowlists will work after that date.

**Comment by bhakimi** [comment]
thanks for the prompt response! excited

**Comment by bc-shopback** [comment]
@thombergs Thanks for the update. 

where can we have the official atlassian IP allowlist ? is the [link](https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/) mentioned in  https://github.com/atlassian/github-for-jira/issues/411#issuecomment-858644847 still valid ?

Thanks!

**Comment by mboudreau** [comment]
That's correct, however, after we do the migration we will enable that ip allowlist in the app itself and should propagate to every github install automatically, so no need to manually input it :)

**Comment by thombergs** [comment]
@maxwolffe @jbonilla-li @KatjaWass @bhakimi @bc-shopback 

We did the migration into the Atlassian infrastructure today and the integration should now work with IP allowlists (I just tested it with a test enterprise org).

You can either add the IP addresses manually (from [this page](https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/) or you can check "Enable IP allowlist configuration for installed GitHub apps" to automatically get the IP addresses from our app (which will save you the trouble of keeping them up-to-date should they ever change).

![image](https://user-images.githubusercontent.com/1363578/130347295-e524955c-84b7-4e22-af45-957897b7cadb.png)

Please test it out! :)

**Comment by yairyog** [comment]
@thombergs
So far looks great! 👍 
Thank you, there were actual hurray shouts in my org :)

**Comment by thombergs** [comment]
@yairyog thanks for the feedback. I'll close this issue then. 🎉

**Comment by barry-ozer** [comment]
It doesn't appear to have backfilled links? Is it possible to backfill links for existing issues, if so how @thombergs?

**Comment by YugoHino** [comment]
In our environment, this still doesn't work. We have GitHub Enterprise and this is working on github.com not on-premise. Under this account, 2 organizations enable ip address allow list and 1 organization is not set this setting. I can connect from Jira to 1 organization, but 2 organizations don't show connect button on Jira app configuration page. We check "Enable IP allow list configuration for installed GitHub Apps" on GitHub organization setting page, and those ip addresses are same as [this page's](https://support.atlassian.com/organization-administration/docs/ip-addresses-and-domains-for-atlassian-cloud-products/)  out going ip addresses. Do we need to set anythingelse?

**Comment by YugoHino** [comment]
Those ip addresses which automatically added are here .
IP address	Description	
104.192.137.240/28	Managed by the Jira GitHub App	
104.192.138.240/28	Managed by the Jira GitHub App	
104.192.140.240/28	Managed by the Jira GitHub App	
104.192.142.240/28	Managed by the Jira GitHub App	
104.192.143.240/28	Managed by the Jira GitHub App	
13.236.8.224/28	Managed by the Jira GitHub App	
13.52.5.96/28	Managed by the Jira GitHub App	
18.136.214.96/28	Managed by the Jira GitHub App	
18.184.99.224/28	Managed by the Jira GitHub App	
18.234.32.224/28	Managed by the Jira GitHub App	
18.246.31.224/28	Managed by the Jira GitHub App	
185.166.142.240/28	Managed by the Jira GitHub App	
185.166.143.240/28	Managed by the Jira GitHub App	
52.215.192.224/28	Managed by the Jira GitHub App
